## Checking DNS Configuration
---
- hosts: all
  gather_facts: false

  roles:
    - akirak.coreos-python

  become: yes

  tasks:
  - name: Check dns configuration
    shell: cat /etc/resolv.conf | grep  -E "nameserver [0-9]+.[0-9]+.[0-9]+.[0-9]+"
    register: output
    failed_when: "output.rc != 0"
